#!/usr/bin/env python3


## ---------------------------------------------------------------------------->
## MLB Stats URL values
## ---------------------------------------------------------------------------->
MLB_STATS_BASE_URL       = 'https://statsapi.mlb.com'
MLB_STATS_SCHEDULE_STUB  = '/api/v1/schedule'
MLB_STATS_GAME_STUB      = '/api/v1/game/<<GAME_PK>>/content'
MLB_STATS_LIVE_FEED_STUB = '/api/v1.1/game/<<GAME_PK>>/feed/live'


## ---------------------------------------------------------------------------->
## Values for the 'game_type' column in the pybaseball.statcast() results.
## ---------------------------------------------------------------------------->

GAME_TYPES = {
    'R': 'Regular season',
    'S': 'Spring training',
    'F': 'Wild card game',
    'D': 'Division series',
    'L': 'League championship series',
    'W': 'World Series',
    'E': 'Exhibition',
    'A': 'All-Star Game',
}

## ---------------------------------------------------------------------------->
## All the teams, their names, divisions, etc.
## ---------------------------------------------------------------------------->

TEAMS = {
    "AZ": {
        "name": "Arizona Diamondbacks",
        "abbreviation": "AZ",
        "location": "Phoenix",
        "teamname": "Diamondbacks",
        "division": "West",
        "league": "National",
        "mlb_id": "109",
    },
    "ATL": {
        "name": "Atlanta Braves",
        "abbreviation": "ATL",
        "location": "Atlanta",
        "teamname": "Braves",
        "division": "East",
        "league": "National",
        "mlb_id": "144",
    },
    "BAL": {
        "name": "Baltimore Orioles",
        "abbreviation": "BAL",
        "location": "Baltimore",
        "teamname": "Orioles",
        "division": "East",
        "league": "American",
        "mlb_id": "110",
    },
    "BOS": {
        "name": "Boston Red Sox",
        "abbreviation": "BOS",
        "location": "Boston",
        "teamname": "Red Sox",
        "division": "East",
        "league": "American",
        "mlb_id": "111",
    },
    "CHC": {
        "name": "Chicago Cubs",
        "abbreviation": "CHC",
        "location": "Chicago",
        "teamname": "Cubs",
        "division": "Central",
        "league": "National",
        "mlb_id": "112",
    },
    "CIN": {
        "name": "Cincinnati Reds",
        "abbreviation": "CIN",
        "location": "Cincinnati",
        "teamname": "Reds",
        "division": "Central",
        "league": "National",
        "mlb_id": "113",
    },
    "CLE": {
        "name": "Cleveland Guardians",
        "abbreviation": "CLE",
        "location": "Cleveland",
        "teamname": "Guardians",
        "division": "Central",
        "league": "American",
        "mlb_id": "114",
    },
    "COL": {
        "name": "Colorado Rockies",
        "abbreviation": "COL",
        "location": "Denver",
        "teamname": "Rockies",
        "division": "West",
        "league": "National",
        "mlb_id": "115",
    },
    "CWS": {
        "name": "Chicago White Sox",
        "abbreviation": "CWS",
        "location": "Chicago",
        "teamname": "White Sox",
        "division": "Central",
        "league": "American",
        "mlb_id": "145",
    },
    "DET": {
        "name": "Detroit Tigers",
        "abbreviation": "DET",
        "location": "Detroit",
        "teamname": "Tigers",
        "division": "Central",
        "league": "American",
        "mlb_id": "116",
    },
    "HOU": {
        "name": "Houston Astros",
        "abbreviation": "HOU",
        "location": "Houston",
        "teamname": "Astros",
        "division": "West",
        "league": "American",
        "mlb_id": "117",
    },
    "KC": {
        "name": "Kansas City Royals",
        "abbreviation": "KC",
        "location": "Kansas City",
        "teamname": "Royals",
        "division": "Central",
        "league": "American",
        "mlb_id": "118",
    },
    "LAA": {
        "name": "Los Angeles Angels",
        "abbreviation": "LAA",
        "location": "Anaheim",
        "teamname": "Angels",
        "division": "West",
        "league": "American",
        "mlb_id": "108",
    },
    "LAD": {
        "name": "Los Angeles Dodgers",
        "abbreviation": "LAD",
        "location": "Los Angeles",
        "teamname": "Dodgers",
        "division": "West",
        "league": "National",
        "mlb_id": "119",
    },
    "MIA": {
        "name": "Miami Marlins",
        "abbreviation": "MIA",
        "location": "Miami",
        "teamname": "Marlins",
        "division": "East",
        "league": "National",
        "mlb_id": "146",
    },
    "MIL": {
        "name": "Milwaukee Brewers",
        "abbreviation": "MIL",
        "location": "Milwaukee",
        "teamname": "Brewers",
        "division": "Central",
        "league": "National",
        "mlb_id": "158",
    },
    "MIN": {
        "name": "Minnesota Twins",
        "abbreviation": "MIN",
        "location": "Minneapolis",
        "teamname": "Twins",
        "division": "Central",
        "league": "American",
        "mlb_id": "142",
    },
    "NYM": {
        "name": "New York Mets",
        "abbreviation": "NYM",
        "location": "Flushing",
        "teamname": "Mets",
        "division": "East",
        "league": "National",
        "mlb_id": "121",
    },
    "NYY": {
        "name": "New York Yankees",
        "abbreviation": "NYY",
        "location": "Bronx",
        "teamname": "Yankees",
        "division": "East",
        "league": "American",
        "mlb_id": "147",
    },
    "ATH": {
        "name": "West Sacramento Athletics",
        "abbreviation": "ATH",
        "location": "West Sacramento",
        "teamname": "Athletics",
        "division": "West",
        "league": "American",
        "mlb_id": "133",
    },
    "PHI": {
        "name": "Philadelphia Phillies",
        "abbreviation": "PHI",
        "location": "Philadelphia",
        "teamname": "Phillies",
        "division": "East",
        "league": "National",
        "mlb_id": "143",
    },
    "PIT": {
        "name": "Pittsburgh Pirates",
        "abbreviation": "PIT",
        "location": "Pittsburgh",
        "teamname": "Pirates",
        "division": "Central",
        "league": "National",
        "mlb_id": "134",
    },
    "SD": {
        "name": "San Diego Padres",
        "abbreviation": "SD",
        "location": "San Diego",
        "teamname": "Padres",
        "division": "West",
        "league": "National",
        "mlb_id": "135",
    },
    "SEA": {
        "name": "Seattle Mariners",
        "abbreviation": "SEA",
        "location": "Seattle",
        "teamname": "Mariners",
        "division": "West",
        "league": "American",
        "mlb_id": "136",
    },
    "SF": {
        "name": "San Francisco Giants",
        "abbreviation": "SF",
        "location": "San Francisco",
        "teamname": "Giants",
        "division": "West",
        "league": "National",
        "mlb_id": "137",
    },
    "STL": {
        "name": "St. Louis Cardinals",
        "abbreviation": "STL",
        "location": "St. Louis",
        "teamname": "Cardinals",
        "division": "Central",
        "league": "National",
        "mlb_id": "138",
    },
    "TB": {
        "name": "Tampa Bay Rays",
        "abbreviation": "TB",
        "location": "St. Petersburg",
        "teamname": "Rays",
        "division": "East",
        "league": "American",
        "mlb_id": "139",
    },
    "TEX": {
        "name": "Texas Rangers",
        "abbreviation": "TEX",
        "location": "Arlington",
        "teamname": "Rangers",
        "division": "West",
        "league": "American",
        "mlb_id": "140",
    },
    "TOR": {
        "name": "Toronto Blue Jays",
        "abbreviation": "TOR",
        "location": "Toronto",
        "teamname": "Blue Jays",
        "division": "East",
        "league": "American",
        "mlb_id": "141",
    },
    "WSH": {
        "name": "Washington Nationals",
        "abbreviation": "WSH",
        "location": "Washington",
        "teamname": "Nationals",
        "division": "East",
        "league": "National",
        "mlb_id": "120",
    },
}
